In [1]:
import pandas as pd

df = pd.read_csv("testdist.tsv", header=None, sep="\t")
df2 = pd.read_csv("dict.tsv", header=None, sep="\t")

df

                      0                1           2
0    NEG+1p+PRES+kuweza  we are not able    hatuwezi
1           2s+IMP+kuja             come        njoo
2           2p+IMP+kuja             come      njooni
3         2s+IMP+kuleta            bring        lete
4         2p+IMP+kuleta            bring      leteni
..                  ...              ...         ...
226    3p+PAST+kufariki        they died  walifariki
227      2s+PRES+kujali         you care     unajali
228     3s+PRES+kusomea    (s)he studies    anasomea
229     3p+PRES+kusomea       they study   wanasomea
230    1s+PRES+kutamani           I wish  ninatamani

[231 rows x 3 columns]

In [6]:
print(*df2[1].tolist(), sep = "\n")

leave
order
tell
believe
awaken
decide
prepare
write
look
fall
start
exchange
carry
disagree
choose
mix
laugh
be late
boil
play
tire
hate
take
go
understand
explain
continue
drive
die
be suitable
resemble
happen
do
die
arrive
arrive at
think
think about
close
open
teach
be happy
share
argue
touch
confirm
feel
need
steal
sing
enter
end
live
be named
come
care
try
build
answer
learn
improve
know
stay
fry
approach
be angry
cut
run
kiss
rent
rent
lose weight
be wrong
agree
grow up
remember
remind
eat
sleep
bring
cry
pay
mean
finish
put on weight
buy
drink
swim
fear
request
see
depart
resemble
speak
add
taste
show
wash
give
plan
get
take
love
prefer
look great
cook
turn
pass
visit
receive
be lost
lose
rest
reduce
repair
report
return
allow
jump
clean
forget
help
pray
say
be full
share
be shocked
recommend
hear
listen
stop
read
study
be required
relax
wait
worry
look for
want
wish
realize
expect
watch
plan
walk
visit
make
subtract
come from
suffice
send
hope
use
kill
ask
bite
be sick
sell
wear
cross
break
communicate
turn on
think
put
be able
be born
turn off
be used to
converse
go
finish

In [7]:
sp = """dejar
orden
decir
creer
despertar
decidir
preparar
escribir
mirar
caer
comenzar
intercambio
llevar
discrepar
elegir
mezcla
reír
llegar tarde
hervir
jugar
neumático
odiar
llevar
ir
entender
explicar
continuar
conducir
morir
ser adecuado
parecerse
suceder
hacer
morir
llegar
llegar a
pensar
pensar en
cerca
abierto
enseñar
ser feliz
compartir
argumentar
tocar
confirmar
sentir
necesidad
robar
cantar
ingresar
fin
vivir
ser nombrado
venir
cuidado
intentar
construir
respuesta
aprender
mejorar
saber
permanecer
freír
acercarse
estar enojado
cortar
correr
beso
alquilar
alquilar
perder peso
estar equivocado
aceptar
crecer
recordar
recordar
comer
dormir
traer
llorar
pagar
significar
finalizar
Poner peso
comprar
beber
nadar
miedo
pedido
ver
salir
parecerse
hablar
agregar
gusto
espectáculo
lavar
dar
plan
conseguir
llevar
amar
preferir
se ve genial
cocinar
doblar
aprobar
visita
recibir
estar perdido
perder
descansar
reducir
reparar
informe
devolver
permitir
saltar
limpio
olvidar
ayuda
orar
decir
estar lleno
compartir
estar conmocionado
recomendar
escuchar
escuchar
detener
leer
estudiar
ser requerido
relajarse
esperar
preocuparse
buscar
desear
desear
darse cuenta
esperar
mirar
plan
caminar
visita
hacer
sustraer
viene de
satisfacer
enviar
esperanza
usar
matar
preguntar
morder
estar enfermo
vender
tener puesto
cruz
romper
comunicar
encender
pensar
poner
ser capaz
nacer
apagar
ser usado para
conversar
ir
finalizar"""

In [10]:
df2[2] = sp.split("\n")

In [12]:
df2.to_csv("dict.tsv", sep="\t", header=None, index=False)

In [31]:
def get_english(feat):
    swahili_word = feat.split("+")[-1]
    # print(swahili_word)
    return df2[df2[0] == swahili_word].values[0][1]

def create_eng_feat(feat):
    return "+".join(feat.split("+")[:-1] )

In [35]:
df[3] = df[0].apply(lambda x:create_eng_feat(x)+"+"+ get_english(x))

In [13]:
df

                      0                1           2
0    NEG+1p+PRES+kuweza  we are not able    hatuwezi
1           2s+IMP+kuja             come        njoo
2           2p+IMP+kuja             come      njooni
3         2s+IMP+kuleta            bring        lete
4         2p+IMP+kuleta            bring      leteni
..                  ...              ...         ...
226    3p+PAST+kufariki        they died  walifariki
227      2s+PRES+kujali         you care     unajali
228     3s+PRES+kusomea    (s)he studies    anasomea
229     3p+PRES+kusomea       they study   wanasomea
230    1s+PRES+kutamani           I wish  ninatamani

[231 rows x 3 columns]

In [39]:
pd.DataFrame(df[[3,1]]).to_csv("test_english_sentences.tsv", sep="\t", header=False, index=False)

In [14]:
df = pd.read_csv("test_english_sentences.tsv", header=None, sep="\t")

In [17]:
trnsln = pd.read_csv("dict.tsv", header=None, sep="\t")

In [27]:
def translate(verb):
    return trnsln.loc[trnsln[1] == verb, 2].iloc[0]

In [24]:
trnsln

              0           1               2
0        kuacha       leave           dejar
1       kuagiza       order           orden
2       kuambia        tell           decir
3       kuamini     believe           creer
4        kuamka      awaken       despertar
..          ...         ...             ...
167      kuzima    turn off          apagar
168      kuzoea  be used to  ser usado para
169  kuzungumza    converse       conversar
170      kwenda          go              ir
171      kwisha      finish       finalizar

[172 rows x 3 columns]

In [28]:
translate("be happy")

'ser feliz'

In [30]:
df

                       0                1
0    NEG+1p+PRES+be able  we are not able
1            2s+IMP+come             come
2            2p+IMP+come             come
3           2s+IMP+bring            bring
4           2p+IMP+bring            bring
..                   ...              ...
226          3p+PAST+die        they died
227         2s+PRES+care         you care
228        3s+PRES+study    (s)he studies
229        3p+PRES+study       they study
230         1s+PRES+wish           I wish

[231 rows x 2 columns]

In [33]:
col0 = df[0].apply(lambda x: "+".join(x.split("+")[:-1])+"+"+translate(x.split("+")[-1]))

In [34]:
col1 = df[0].apply(lambda x: translate(x.split("+")[-1]))

In [35]:
pd.DataFrame([col0, col1]).T.to_csv("test_spanish_sentences.tsv", sep="\t", header=False, index=False)